export const learningLevelOneItems = [
  {
    id: "ha",
    aksara: "\u1BA0",
    latin: "ha",
    title: "Huruf Ha",
    note: "Huruf pembuka yang sering dikenalkan pertama.",
    audioSrc: "/assets/audio/ha.wav",
  },
  {
    id: "na",
    aksara: "\u1B94",
    latin: "na",
    title: "Huruf Na",
    note: "Bentuknya mudah dikenali dan cocok untuk latihan awal.",
    audioSrc: "/assets/audio/na.wav",
  },
  {
    id: "ca",
    aksara: "\u1B8E",
    latin: "ca",
    title: "Huruf Ca",
    note: "Latihan pengenalan bentuk dan sebutan.",
    audioSrc: "/assets/audio/ca.wav",
  },
  {
    id: "ra",
    aksara: "\u1B9B",
    latin: "ra",
    title: "Huruf Ra",
    note: "Mulai masuk ke variasi lengkung aksara.",
    audioSrc: "/assets/audio/ra.wav",
  },
  {
    id: "ka",
    aksara: "\u1B8A",
    latin: "ka",
    title: "Huruf Ka",
    note: "Cocok dipakai untuk latihan baca dan kuis awal.",
    audioSrc: "/assets/audio/ka.wav",
  },
] as const;

export const learningNumberItems = [
  {
    id: "one",
    aksara: "\u1BB1",
    latin: "1",
    title: "Angka Hiji",
    note: "Ieu mangrupa angka hiji dina aksara Sunda.",
  },
  {
    id: "three",
    aksara: "\u1BB3",
    latin: "3",
    title: "Angka Tilu",
    note: "Bisa dipake pikeun latihan maca angka dasar.",
  },
  {
    id: "five",
    aksara: "\u1BB5",
    latin: "5",
    title: "Angka Lima",
    note: "Wangun angka ieu alus pikeun dibiasakeun dina kuis.",
  },
  {
    id: "seven",
    aksara: "\u1BB7",
    latin: "7",
    title: "Angka Tujuh",
    note: "Ngabantu ngenalkeun runtuyan angka Sunda leuwih jauh.",
  },
  {
    id: "nine",
    aksara: "\u1BB9",
    latin: "9",
    title: "Angka Salapan",
    note: "Sok dipake dina latihan campuran hurup jeung angka.",
  },
] as const;

export const quizLevelOneQuestions = [
  {
    id: "q1",
    aksara: "\u1B8A",
    prompt: "Pilih jawaban yang sesuai dengan aksara Sunda berikut.",
    options: ["ka", "pa", "sa", "ta"],
    answer: "ka",
  },
  {
    id: "q2",
    aksara: "\u1BA0",
    prompt: "Aksara ini dibaca apa?",
    options: ["ha", "da", "ya", "ba"],
    answer: "ha",
  },
  {
    id: "q3",
    aksara: "\u1B94",
    prompt: "Pilih bacaan latin yang benar.",
    options: ["ca", "ra", "na", "ga"],
    answer: "na",
  },
  {
    id: "q4",
    aksara: "\u1B8E",
    prompt: "Huruf ini mewakili bunyi apa?",
    options: ["ja", "ca", "wa", "la"],
    answer: "ca",
  },
  {
    id: "q5",
    aksara: "\u1B9B",
    prompt: "Jawaban yang benar untuk aksara ini adalah...",
    options: ["ra", "ma", "ta", "ka"],
    answer: "ra",
  },
  {
    id: "q6",
    aksara: "\u1BB1",
    prompt: "Ini adalah angka Sunda berapa?",
    options: ["1", "2", "3", "4"],
    answer: "1",
  },
  {
    id: "q7",
    aksara: "\u1BB3",
    prompt: "Pilih angka latin yang sesuai.",
    options: ["2", "4", "3", "7"],
    answer: "3",
  },
  {
    id: "q8",
    aksara: "\u1BB5",
    prompt: "Angka Sunda ini dibaca...",
    options: ["4", "5", "6", "8"],
    answer: "5",
  },
  {
    id: "q9",
    aksara: "\u1BB7",
    prompt: "Jawaban angka yang benar adalah...",
    options: ["6", "7", "8", "9"],
    answer: "7",
  },
  {
    id: "q10",
    aksara: "\u1BB9",
    prompt: "Aksara angka ini menunjukkan bilangan...",
    options: ["7", "8", "9", "0"],
    answer: "9",
  },
] as const;
